<a href="https://colab.research.google.com/github/Rishavh-dev/ML_Models/blob/Machine_Learning/Dropped_Out_Student.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("student dropout.csv")

In [3]:
df

,School,Gender,Age,Address,Family_Size,Parental_Status,Mother_Education,Father_Education,Mother_Job,Father_Job,...,Free_Time,Going_Out,Weekend_Alcohol_Consumption,Weekday_Alcohol_Consumption,Health_Status,Number_of_Absences,Grade_1,Grade_2,Final_Grade,Dropped_Out
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,3,4,1,1,3,4,0,11,11,False
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,3,1,1,3,2,9,11,11,False
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,3,2,2,3,3,6,12,13,12,False
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,2,1,1,5,0,14,14,14,False
4,GP,F,16,U,GT3,T,3,3,other,other,...,3,2,1,2,5,0,11,13,13,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,MS,F,19,R,GT3,T,2,3,services,other,...,4,2,1,2,5,4,10,11,10,False
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,3,4,1,1,1,4,15,15,16,False
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,5,6,11,12,9,True
647,MS,M,17,U,LE3,T,3,1,services,services,...,4,5,3,4,2,6,10,10,10,False
648,MS,M,18,R,LE3,T,3,2,services,other,...,4,1,3,4,5,4,10,11,11,False

In [4]:
df.columns

Index(['School', 'Gender', 'Age', 'Address', 'Family_Size', 'Parental_Status',
       'Mother_Education', 'Father_Education', 'Mother_Job', 'Father_Job',
       'Reason_for_Choosing_School', 'Guardian', 'Travel_Time', 'Study_Time',
       'Number_of_Failures', 'School_Support', 'Family_Support',
       'Extra_Paid_Class', 'Extra_Curricular_Activities', 'Attended_Nursery',
       'Wants_Higher_Education', 'Internet_Access', 'In_Relationship',
       'Family_Relationship', 'Free_Time', 'Going_Out',
       'Weekend_Alcohol_Consumption', 'Weekday_Alcohol_Consumption',
       'Health_Status', 'Number_of_Absences', 'Grade_1', 'Grade_2',
       'Final_Grade', 'Dropped_Out'],
      dtype='object')

In [5]:
df.isnull().sum()

School                         0
Gender                         0
Age                            0
Address                        0
Family_Size                    0
Parental_Status                0
Mother_Education               0
Father_Education               0
Mother_Job                     0
Father_Job                     0
Reason_for_Choosing_School     0
Guardian                       0
Travel_Time                    0
Study_Time                     0
Number_of_Failures             0
School_Support                 0
Family_Support                 0
Extra_Paid_Class               0
Extra_Curricular_Activities    0
Attended_Nursery               0
Wants_Higher_Education         0
Internet_Access                0
In_Relationship                0
Family_Relationship            0
Free_Time                      0
Going_Out                      0
Weekend_Alcohol_Consumption    0
Weekday_Alcohol_Consumption    0
Health_Status                  0
Number_of_Absences             0
Grade_1                        0
Grade_2                        0
Final_Grade                    0
Dropped_Out                    0
dtype: int64

In [6]:
#Finding Non_numerical Columns
non_num = df.select_dtypes(exclude=[np.number])
print(non_num)

    School Gender Address Family_Size Parental_Status Mother_Job Father_Job  \
0       GP      F       U         GT3               A    at_home    teacher
1       GP      F       U         GT3               T    at_home      other
2       GP      F       U         LE3               T    at_home      other
3       GP      F       U         GT3               T     health   services
4       GP      F       U         GT3               T      other      other
..     ...    ...     ...         ...             ...        ...        ...
644     MS      F       R         GT3               T   services      other
645     MS      F       U         LE3               T    teacher   services
646     MS      F       U         GT3               T      other      other
647     MS      M       U         LE3               T   services   services
648     MS      M       R         LE3               T   services      other

    Reason_for_Choosing_School Guardian School_Support Family_Support  \
0                       course   mother            yes             no
1                       course   father             no            yes
2                        other   mother            yes             no
3                         home   mother             no            yes
4                         home   father             no            yes
..                         ...      ...            ...            ...
644                     course   mother             no             no
645                     course   mother             no            yes
646                     course   mother             no             no
647                     course   mother             no             no
648                     course   mother             no             no

    Extra_Paid_Class Extra_Curricular_Activities Attended_Nursery  \
0                 no                          no              yes
1                 no                          no               no
2                 no                          no              yes
3                 no                         yes              yes
4                 no                          no              yes
..               ...                         ...              ...
644               no                         yes               no
645               no                          no              yes
646               no                         yes              yes
647               no                          no               no
648               no                          no               no

    Wants_Higher_Education Internet_Access In_Relationship  Dropped_Out
0                      yes              no              no        False
1                      yes             yes              no        False
2                      yes             yes              no        False
3                      yes             yes             yes        False
4                      yes              no              no        False
..                     ...             ...             ...          ...
644                    yes             yes              no        False
645                    yes             yes              no        False
646                    yes              no              no         True
647                    yes             yes              no        False
648                    yes             yes              no        False

[649 rows x 18 columns]

In [8]:
cat_cols = ['School', 'Gender', 'Address', 'Family_Size', 'Parental_Status', 'Mother_Job', 'Father_Job', 'Reason_for_Choosing_School', 'Guardian', 'School_Support', 'Family_Support', 'Extra_Paid_Class', 'Extra_Curricular_Activities', 'Attended_Nursery', 'Wants_Higher_Education', 'Internet_Access', 'In_Relationship', 'Dropped_Out']

In [9]:
new_df = pd.get_dummies(df[cat_cols], drop_first=False).astype(int)

In [10]:
new_df

,Dropped_Out,School_GP,School_MS,Gender_F,Gender_M,Address_R,Address_U,Family_Size_GT3,Family_Size_LE3,Parental_Status_A,...,Extra_Curricular_Activities_no,Extra_Curricular_Activities_yes,Attended_Nursery_no,Attended_Nursery_yes,Wants_Higher_Education_no,Wants_Higher_Education_yes,Internet_Access_no,Internet_Access_yes,In_Relationship_no,In_Relationship_yes
0,0,1,0,1,0,0,1,1,0,1,...,1,0,0,1,0,1,1,0,1,0
1,0,1,0,1,0,0,1,1,0,0,...,1,0,1,0,0,1,0,1,1,0
2,0,1,0,1,0,0,1,0,1,0,...,1,0,0,1,0,1,0,1,1,0
3,0,1,0,1,0,0,1,1,0,0,...,0,1,0,1,0,1,0,1,0,1
4,0,1,0,1,0,0,1,1,0,0,...,1,0,0,1,0,1,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,0,0,1,1,0,1,0,1,0,0,...,0,1,1,0,0,1,0,1,1,0
645,0,0,1,1,0,0,1,0,1,0,...,1,0,0,1,0,1,0,1,1,0
646,1,0,1,1,0,0,1,1,0,0,...,0,1,0,1,0,1,1,0,1,0
647,0,0,1,0,1,0,1,0,1,0,...,1,0,1,0,0,1,0,1,1,0
648,0,0,1,0,1,1,0,0,1,0,...,1,0,1,0,0,1,0,1,1,0

In [11]:
df

,School,Gender,Age,Address,Family_Size,Parental_Status,Mother_Education,Father_Education,Mother_Job,Father_Job,...,Free_Time,Going_Out,Weekend_Alcohol_Consumption,Weekday_Alcohol_Consumption,Health_Status,Number_of_Absences,Grade_1,Grade_2,Final_Grade,Dropped_Out
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,3,4,1,1,3,4,0,11,11,False
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,3,1,1,3,2,9,11,11,False
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,3,2,2,3,3,6,12,13,12,False
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,2,1,1,5,0,14,14,14,False
4,GP,F,16,U,GT3,T,3,3,other,other,...,3,2,1,2,5,0,11,13,13,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,MS,F,19,R,GT3,T,2,3,services,other,...,4,2,1,2,5,4,10,11,10,False
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,3,4,1,1,1,4,15,15,16,False
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,5,6,11,12,9,True
647,MS,M,17,U,LE3,T,3,1,services,services,...,4,5,3,4,2,6,10,10,10,False
648,MS,M,18,R,LE3,T,3,2,services,other,...,4,1,3,4,5,4,10,11,11,False

In [12]:
df.drop(df[cat_cols],axis=1,inplace=True)

In [13]:
new_data = pd.concat([df,new_df],axis=True)

In [14]:
new_data

,Age,Mother_Education,Father_Education,Travel_Time,Study_Time,Number_of_Failures,Family_Relationship,Free_Time,Going_Out,Weekend_Alcohol_Consumption,...,Extra_Curricular_Activities_no,Extra_Curricular_Activities_yes,Attended_Nursery_no,Attended_Nursery_yes,Wants_Higher_Education_no,Wants_Higher_Education_yes,Internet_Access_no,Internet_Access_yes,In_Relationship_no,In_Relationship_yes
0,18,4,4,2,2,0,4,3,4,1,...,1,0,0,1,0,1,1,0,1,0
1,17,1,1,1,2,0,5,3,3,1,...,1,0,1,0,0,1,0,1,1,0
2,15,1,1,1,2,0,4,3,2,2,...,1,0,0,1,0,1,0,1,1,0
3,15,4,2,1,3,0,3,2,2,1,...,0,1,0,1,0,1,0,1,0,1
4,16,3,3,1,2,0,4,3,2,1,...,1,0,0,1,0,1,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,19,2,3,1,3,1,5,4,2,1,...,0,1,1,0,0,1,0,1,1,0
645,18,3,1,1,2,0,4,3,4,1,...,1,0,0,1,0,1,0,1,1,0
646,18,1,1,2,2,0,1,1,1,1,...,0,1,0,1,0,1,1,0,1,0
647,17,3,1,2,1,0,2,4,5,3,...,1,0,1,0,0,1,0,1,1,0
648,18,3,2,3,1,0,4,4,1,3,...,1,0,1,0,0,1,0,1,1,0

In [15]:
new_data.columns

Index(['Age', 'Mother_Education', 'Father_Education', 'Travel_Time',
       'Study_Time', 'Number_of_Failures', 'Family_Relationship', 'Free_Time',
       'Going_Out', 'Weekend_Alcohol_Consumption',
       'Weekday_Alcohol_Consumption', 'Health_Status', 'Number_of_Absences',
       'Grade_1', 'Grade_2', 'Final_Grade', 'Dropped_Out', 'School_GP',
       'School_MS', 'Gender_F', 'Gender_M', 'Address_R', 'Address_U',
       'Family_Size_GT3', 'Family_Size_LE3', 'Parental_Status_A',
       'Parental_Status_T', 'Mother_Job_at_home', 'Mother_Job_health',
       'Mother_Job_other', 'Mother_Job_services', 'Mother_Job_teacher',
       'Father_Job_at_home', 'Father_Job_health', 'Father_Job_other',
       'Father_Job_services', 'Father_Job_teacher',
       'Reason_for_Choosing_School_course', 'Reason_for_Choosing_School_home',
       'Reason_for_Choosing_School_other',
       'Reason_for_Choosing_School_reputation', 'Guardian_father',
       'Guardian_mother', 'Guardian_other', 'School_Support_no',
       'School_Support_yes', 'Family_Support_no', 'Family_Support_yes',
       'Extra_Paid_Class_no', 'Extra_Paid_Class_yes',
       'Extra_Curricular_Activities_no', 'Extra_Curricular_Activities_yes',
       'Attended_Nursery_no', 'Attended_Nursery_yes',
       'Wants_Higher_Education_no', 'Wants_Higher_Education_yes',
       'Internet_Access_no', 'Internet_Access_yes', 'In_Relationship_no',
       'In_Relationship_yes'],
      dtype='object')

In [16]:
aa= new_data['Dropped_Out']

In [17]:
aa

0      0
1      0
2      0
3      0
4      0
      ..
644    0
645    0
646    1
647    0
648    0
Name: Dropped_Out, Length: 649, dtype: int64

In [18]:
#Modelling

In [19]:
x=new_data.drop('Dropped_Out',axis=1)
y=new_data['Dropped_Out']

In [20]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [22]:
print(x_train.shape, y_train.shape)

(519, 59) (519,)

In [23]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

LogisticRegression()

In [24]:
y_pred=lr.predict(x_test)

In [25]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1])

In [26]:
lr.score(x_train,y_train)

0.9961464354527938

In [27]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [28]:
confusion_matrix(y_test,y_pred)

array([[113,   2],
       [  2,  13]])

In [29]:
accuracy_score(y_test,y_pred)

0.9692307692307692

In [30]:
report=classification_report(y_test,y_pred)

In [31]:
import pprint

In [32]:
pprint.pprint(report)

('              precision    recall  f1-score   support\n'
 '\n'
 '           0       0.98      0.98      0.98       115\n'
 '           1       0.87      0.87      0.87        15\n'
 '\n'
 '    accuracy                           0.97       130\n'
 '   macro avg       0.92      0.92      0.92       130\n'
 'weighted avg       0.97      0.97      0.97       130\n')

In [33]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [34]:
!pip install ghapi

Collecting ghapi
  Downloading ghapi-1.0.6-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from ghapi) (24.1)
Requirement already satisfied: fastcore>=1.7.2 in /usr/local/lib/python3.10/dist-packages (from ghapi) (1.7.8)
Downloading ghapi-1.0.6-py3-none-any.whl (62 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.4/62.4 kB 2.7 MB/s eta 0:00:00
Installing collected packages: ghapi
Successfully installed ghapi-1.0.6

In [36]:
!git init
!git add .
!git config --global user.email "rds98890@gmail.com"
!git config --global user.name "Rishavh-dev"
!git commit -m "Initial commit"
!git branch -m main
!git remote add origin https://github.com/Rishavh-dev/ML_Models.git
!git push origin main

Reinitialized existing Git repository in /content/.git/
[master (root-commit) d50eae7] Initial commit
 142 files changed, 51837 insertions(+)
 create mode 100644 .config/.last_opt_in_prompt.yaml
 create mode 100644 .config/.last_survey_prompt.yaml
 create mode 100644 .config/.last_update_check.json
 create mode 100644 .config/active_config
 create mode 100644 .config/config_sentinel
 create mode 100644 .config/configurations/config_default
 create mode 100644 .config/default_configs.db
 create mode 100644 .config/gce
 create mode 100644 .config/hidden_gcloud_config_universe_descriptor_data_cache_configs.db
 create mode 100644 .config/logs/2024.09.20/13.21.13.139283.log
 create mode 100644 .config/logs/2024.09.20/13.21.34.104159.log
 create mode 100644 .config/logs/2024.09.20/13.21.44.777817.log
 create mode 100644 .config/logs/2024.09.20/13.21.45.853413.log
 create mode 100644 .config/logs/2024.09.20/13.21.56.246468.log
 create mode 100644 .config/logs/2024.09.20/13.21.56.905204.log
 create mode 100644 drive/MyDrive/Colab Notebooks/Copy of Dtree (1).ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Copy of EDA (2).ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Copy of K Means Clustering  (1).ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Copy of KNN .ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Copy of KNN_(2)_(1).ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Copy of Logistic Regression.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Copy of NUM_PY part-2.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Copy of RANDOM FOREST (2).ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Copy of Support Vector Machines (2) (1).ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Copy of Support Vector Machines (2).ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Copy of linear regreaaion_06_ml.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Copy of pandassssss.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Copy of visualization.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/DSA_Practice
 create mode 100644 drive/MyDrive/Colab Notebooks/Heart_Disease_Prediction.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Numpy_Pandas_MatPlotLib.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Opencv_Mini_project_1.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Placement 2023.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Songs_prediction.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled (1)
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled0.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled1.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled10.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled11.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled12.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled13.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled14.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled15.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled16.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled17.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled18.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled19.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled2.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled20.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled21.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled22.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled23.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled24.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled25.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled26.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled27.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled28.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled29.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled3.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled30.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled31.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled32.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled33.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled34.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled35.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled36.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled37.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled38.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled39.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled4.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled40.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled41.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled42.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled43.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled44.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled45.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled46.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled47.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled48.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled49.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled5.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled50.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled51.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled52.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled53.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled54.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled55.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled56.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled57.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled58.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled59.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled6.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled60.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled61.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled62.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled63.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled64.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled65.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled66.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled67.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled68.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled69.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled7.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled70.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled71.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled72.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled73.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled74.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled75.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled76.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled77.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled78.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled8.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/Untitled9.ipynb
 create mode 100644 drive/MyDrive/Colab Notebooks/crome_dino_game.ipynb
 create mode 100644 drive/MyDrive/Getting started.pdf
 create mode 100644 drive/MyDrive/IMG_20200604_205657.jpg
 create mode 100644 drive/MyDrive/IMG_20200604_205734 (1).jpg
 create mode 100644 drive/MyDrive/IMG_20200604_205734.jpg
 create mode 100644 drive/MyDrive/Rishabh DevSingh_InternshalaResume.pdf
 create mode 100644 drive/MyDrive/Rishabh DevSingh_Resume.pdf
 create mode 100644 drive/MyDrive/Rishabh dev Singh_CSBS_2022.pdf
 create mode 100644 drive/MyDrive/Rishabh dev Singh_CSBS_2023 (1).pdf
 create mode 100644 drive/MyDrive/Rishabh dev Singh_CSBS_2023 (2).pdf
 create mode 100644 drive/MyDrive/Rishabh dev Singh_CSBS_2023 (3).pdf
 create mode 100644 drive/MyDrive/Rishabh dev Singh_CSBS_2023.pdf
 create mode 100644 drive/MyDrive/question.1.cpp
 create mode 100644 drive/MyDrive/question.2.py
 create mode 100644 drive/MyDrive/rishabh_dev_singh_2023 (1).pdf
 create mode 100644 drive/MyDrive/rishabh_dev_singh_2023 (2).pdf
 create mode 100644 drive/MyDrive/rishabh_dev_singh_2023 (3).pdf
 create mode 100644 drive/MyDrive/rishabh_dev_singh_2023 (4).pdf
 create mode 100644 drive/MyDrive/rishabh_dev_singh_2023.pdf
 create mode 100644 drive/MyDrive/zomato.csv
 create mode 100755 sample_data/README.md
 create mode 100755 sample_data/anscombe.json
 create mode 100644 sample_data/california_housing_test.csv
 create mode 100644 sample_data/california_housing_train.csv
 create mode 100644 sample_data/mnist_test.csv
 create mode 100644 sample_data/mnist_train_small.csv
 create mode 100644 student dropout.csv
error: remote origin already exists.
fatal: could not read Username for 'https://github.com': No such device or address

In [37]:
!git remote remove origin
!git remote add origin https://github.com/Rishavh-dev/ML_Models.git
!git config --global credential.helper store
!git config --global credential.helper cache
!git push origin main

fatal: could not read Username for 'https://github.com': No such device or address